table Customer

	column 'Address Line 1'
		dataType: String
		displayFolder: ""Folder 2!""
		summarizeBy: None
		sourceColumn: Address Line 1

		annotation SummarizationSetBy = Automatic

	column 'Address Line 2'
		dataType: String
		displayFolder: "With Space "
		summarizeBy: None
		sourceColumn: Address Line 2

		annotation SummarizationSetBy = Automatic

	column 'Birth Date'
		dataType: DateTime
		formatString = Long Date
		summarizeBy: None
		sourceColumn: Birth Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Cars Owned'
		dataType: Int64
		displayFolder: 'Folder 1'\"Sub-Folder"
		summarizeBy: Sum
		sourceColumn: Cars Owned

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Number of chldren at home
	column 'Children At Home'
		dataType: Int64
		summarizeBy: Sum
		sourceColumn: Children At Home

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column City
		dataType: String
		dataCategory: City
		summarizeBy: None
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Company Name'
		dataType: String
		summarizeBy: None
		sourceColumn: Company Name

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: String
		dataCategory: Continent
		summarizeBy: None
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

	column CountryRegion
		dataType: String
		dataCategory: Country
		summarizeBy: None
		sourceColumn: CountryRegion

		annotation SummarizationSetBy = Automatic

	column 'Customer Code'
		dataType: String
		dataCategory: PostalCode
		summarizeBy: None
		sourceColumn: Customer Code

		annotation SummarizationSetBy = Automatic

	column 'Customer Type'
		dataType: String
		summarizeBy: None
		sourceColumn: Customer Type

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: Int64
		isHidden
		summarizeBy: None
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date First Purchase'
		dataType: DateTime
		formatString = Long Date
		summarizeBy: None
		sourceColumn: Date First Purchase

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Education
		dataType: String
		summarizeBy: None
		sourceColumn: Education

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: String
		summarizeBy: None
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column 'House Ownership'
		dataType: String
		summarizeBy: None
		sourceColumn: House Ownership

		annotation SummarizationSetBy = Automatic

	column 'Marital Status'
		dataType: String
		summarizeBy: None
		sourceColumn: Marital Status

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: String
		summarizeBy: None
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: String
		summarizeBy: None
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column Phone
		dataType: String
		summarizeBy: None
		sourceColumn: Phone

		annotation SummarizationSetBy = Automatic

	/// The Customer State
	/// 2nd line
	column State
		dataType: String
		summarizeBy: None
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: String
		summarizeBy: None
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column 'Total Children'
		dataType: Int64
		summarizeBy: Sum
		sourceColumn: Total Children

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Yearly Income'
		dataType: Double
		formatString = #,0.00
		summarizeBy: None
		sourceColumn: Yearly Income

		annotation SummarizationSetBy = Automatic

	partition Customer = M
		mode: Import
		expression =
			let
			    Source = Web.Contents(#"[SourceUrl]", [RelativePath = "pbi-tools/contoso-sales-model/main/data/Customer.csv"]),
			    Csv = Csv.Document(Source, [QuoteStyle=QuoteStyle.Csv]),
			    #"Promoted Headers" = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),
			    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"Customer Code", type text}, {"Title", type text}, {"Name", type text}, {"Marital Status", type text}, {"Gender", type text}, {"Yearly Income", type number}, {"Total Children", Int64.Type}, {"Children At Home", Int64.Type}, {"Education", type text}, {"Occupation", type text}, {"House Ownership", type text}, {"Cars Owned", Int64.Type}, {"Continent", type text}, {"City", type text}, {"State", type text}, {"CountryRegion", type text}, {"Address Line 1", type text}, {"Address Line 2", type text}, {"Phone", type text}, {"Customer Type", type text}, {"Company Name", type text}}),
			    #"Parsed Date" = Table.TransformColumns(#"Changed Type",{{"Birth Date", each Date.From(DateTimeZone.From(_)), type date}, {"Date First Purchase", each Date.From(DateTimeZone.From(_)), type date}})
			in
			    #"Parsed Date"

