table Sales

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: year
		rollingWindowPeriods: 5
		incrementalGranularity: day
		incrementalPeriods: 7
		sourceExpression =
			let
			    Source = Web.Contents(#"[SourceUrl]", [RelativePath = "pbi-tools/contoso-sales-model/main/data/Sales.csv"]),
			    Csv = Csv.Document(Source),
			    #"Promoted Headers" = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),
			    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StoreKey", Int64.Type}, {"ProductKey", Int64.Type}, {"PromotionKey", Int64.Type}, {"CurrencyKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"OrderDateKey", Int64.Type},{"Order Line Number", Int64.Type}, {"Quantity", Int64.Type}, {"Unit Price", type number}, {"Unit Discount", type number}, {"Unit Cost", type number}, {"Net Price", type number}}),
			    #"Parsed Date" = Table.TransformColumns(#"Changed Type",{{"Delivery Date", each Date.From(DateTimeZone.From(_)), type date}, {"Order Date", each Date.From(DateTimeZone.From(_)), type date}}),
			    Filtered_Date = if #"[FilterDate]" = null then #"Parsed Date" else Table.SelectRows(#"Parsed Date", each [Order Date] >= #"[FilterDate]")
			in
			    Filtered_Date

	measure Margin = [Sales Amount] - [Cost]
		formatString: "$"#,0
		displayFolder: Measures

		detailRowsDefinition =
				ADDCOLUMNS (
				    NATURALINNERJOIN (
				        DETAILROWS ( [Sales Amount] ),
				        DETAILROWS ( [Cost] )
				    ),
				    "Line Margin", [Line Amount] - [Line Cost]
				)

		annotation PBI_FormatHint = {"isCustom":true}

		annotation PBI_ChangedProperties = ["FormatString"]

	measure 'Sales Amount' = SUMX ( Sales, Sales[Quantity] * Sales[Net Price] )
		displayFolder: Measures

		detailRowsDefinition =
				SELECTCOLUMNS (
				    Sales,
				    "Order Date", Sales[Order Date],
				    "Order Number", Sales[Order Number]
				        & REPT ( "0", LEN ( Sales[Order Number] ) - 5 )
				        & Sales[Order Number],
				    "Order Line Number", Sales[Order Line Number],
				    "Quantity", Sales[Quantity],
				    "Net Price", Sales[Net Price],
				    "Line Amount", Sales[Quantity] * Sales[Net Price],
				    "Product Code", RELATED ( 'Product'[Product Code] ),
				    "Product Name", RELATED ( 'Product'[Product Name] ),
				    "Store Name", RELATED ( Store[Store Name] ),
				    "Store City", RELATED ( Store[City] ),
				    "Customer Code", RELATED ( Customer[Customer Code] ),
				    "Customer Name", RELATED ( Customer[Name] )
				)

		formatStringDefinition = IF ( SELECTEDMEASURE() <= 1E6, "#0,.00", "#0,,.00 M" )

		annotation PBI_ChangedProperties = ["FormatString"]

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Sales Quantity' = SUM ( Sales[Quantity] )
		formatString: #,##0
		displayFolder: Measures

	measure Cost = SUMX ( Sales, Sales[Quantity] * Sales[Unit Cost] )
		formatString: "$"#,0
		displayFolder: Measures

		detailRowsDefinition =
				SELECTCOLUMNS (
				    Sales,
				    "Order Date", Sales[Order Date],
				    "Order Number", Sales[Order Number],
				    "Order Line Number", Sales[Order Line Number],
				    "Quantity", Sales[Quantity],
				    "Unit Cost", Sales[Unit Cost],
				    "Line Cost", Sales[Quantity] * Sales[Unit Cost],
				    "Product Code", RELATED ( 'Product'[Product Code] ),
				    "Product Name", RELATED ( 'Product'[Product Name] ),
				    "Manufacturer", RELATED ( 'Product'[Manufacturer] )
				)

		annotation PBI_FormatHint = {"isCustom":true}

		annotation PBI_ChangedProperties = ["FormatString"]

	column CurrencyKey
		dataType: int64
		isHidden
		summarizeBy: count
		sourceColumn: CurrencyKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CustomerKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Delivery Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		summarizeBy: none
		sourceColumn: Delivery Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Net Price'
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum
		sourceColumn: Net Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Order Date'
		dataType: dateTime
		isHidden
		formatString: Long Date
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Order Line Number'
		dataType: int64
		isHidden
		summarizeBy: sum
		sourceColumn: Order Line Number

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Order Number'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Order Number

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		isHidden
		summarizeBy: count
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PromotionKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: PromotionKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		isHidden
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column StoreKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Cost'
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum
		sourceColumn: Unit Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Unit Discount'
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum
		sourceColumn: Unit Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Unit Price'
		dataType: double
		isHidden
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column SalesAmount = Sales[Quantity] * Sales[Unit Price]
		formatString: 0.00
		lineageTag: 6c85b809-bceb-4982-a951-055e754fedbc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column TotalProductCost = Sales[Quantity] * Sales[Unit Cost]
		formatString: 0.00
		lineageTag: 7118d6d5-46a3-4d52-9267-fcff6ce17e6a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column GrossMargin = Sales[SalesAmount] - Sales[TotalProductCost]
		formatString: 0.00
		lineageTag: 516e4bdd-cd0d-4987-851e-30f2edaaff0a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column GrossMarginPct = DIVIDE ( Sales[GrossMargin], Sales[SalesAmount] )
		formatString: 0%;-0%;0%
		lineageTag: 6a8cb3b0-8f49-4e2b-af64-a77bc59c2f52
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Sales-fae7d1f1-9ede-41b7-b875-8dda67703e5e = m
		mode: import

