table Store

	column 'Address Line 1'
		dataType: String
		summarizeBy: None
		sourceColumn: Address Line 1

		annotation SummarizationSetBy = Automatic

	column 'Address Line 2'
		dataType: String
		summarizeBy: None
		sourceColumn: Address Line 2

		annotation SummarizationSetBy = Automatic

	column City
		dataType: String
		dataCategory: City
		summarizeBy: None
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Close Date'
		dataType: DateTime
		formatString = Long Date
		summarizeBy: None
		sourceColumn: Close Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Close Reason'
		dataType: String
		summarizeBy: None
		sourceColumn: Close Reason

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: String
		dataCategory: Continent
		summarizeBy: None
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

	column CountryRegion
		dataType: String
		dataCategory: Country
		summarizeBy: None
		sourceColumn: CountryRegion

		annotation SummarizationSetBy = Automatic

	/// Number of active store employees
	column Employees
		dataType: Int64
		summarizeBy: Sum
		sourceColumn: Employees

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Last Remodel Date'
		dataType: DateTime
		formatString = Long Date
		summarizeBy: None
		sourceColumn: Last Remodel Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Open Date'
		dataType: DateTime
		formatString = Long Date
		summarizeBy: None
		sourceColumn: Open Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Selling Area'
		dataType: Double
		summarizeBy: None
		sourceColumn: Selling Area

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column State
		dataType: String
		summarizeBy: None
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: String
		summarizeBy: None
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Store Name'
		dataType: String
		summarizeBy: None
		sourceColumn: Store Name

		annotation SummarizationSetBy = Automatic

	column 'Store Phone'
		dataType: String
		summarizeBy: None
		sourceColumn: Store Phone

		annotation SummarizationSetBy = Automatic

	column 'Store Type'
		dataType: String
		summarizeBy: None
		sourceColumn: Store Type

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: Int64
		isHidden
		summarizeBy: None
		sourceColumn: StoreKey

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Zip Code Extension'
		dataType: String
		dataCategory: PostalCode
		summarizeBy: None
		sourceColumn: Zip Code Extension

		annotation SummarizationSetBy = Automatic

	column 'Zip Code'
		dataType: String
		summarizeBy: None
		sourceColumn: Zip Code

		annotation SummarizationSetBy = Automatic

	partition Store = M
		mode: Import
		expression =
			let
			    Source = Web.Contents(#"[SourceUrl]", [RelativePath = "pbi-tools/contoso-sales-model/main/data/Store.csv"]),
			    Csv = Csv.Document(Source),
			    #"Promoted Headers" = Table.PromoteHeaders(Csv, [PromoteAllScalars=true]),
			    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StoreKey", Int64.Type}, {"Store Type", type text}, {"Store Name", type text}, {"Status", type text}, {"Zip Code", type text}, {"Zip Code Extension", type text}, {"Store Phone", type text}, {"Continent", type text}, {"City", type text}, {"State", type text}, {"CountryRegion", type text}, {"Address Line 1", type text}, {"Address Line 2", type text}, {"Close Reason", type text}, {"Employees", Int64.Type}, {"Selling Area", type number}}),
			    #"Parsed Date" = Table.TransformColumns(#"Changed Type",{{"Open Date", each Date.From(DateTimeZone.From(_)), type date}, {"Close Date", each Date.From(DateTimeZone.From(_)), type date}, {"Last Remodel Date", each Date.From(DateTimeZone.From(_)), type date}})
			in
			    #"Parsed Date"

